### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by jrahaim** [jjacobson93/RethinkDBSwift#1]
Platform: Linux

Trying to connect to a RethinkDB running on the local server. I get invalid password on every connection attempt. I CAN connect to the server from a remote host using a different RethinkDB Swift driver (that doesn't support Linux unfortunately).  

```swift
let conn =  try r.connect(db: "testing", user: "admin", password: "XXXXXXXX")
```

I have tried specifying the DB, and not. I even tried adding a new account with no password. Same error. The server DOES have SSL/TLS with valid certs.

Edit: I am able to connect to the DB from PHP on the same server with the same credentials:
```php
$ops["host"] = 'localhost';
$ops["user"] = 'admin';
$ops["password"] = "XXXXXXX";
$ops["db"] = "testing";

$conn = r\connect($ops);
```

**Comment by jjacobson93** [comment]
I'm sorry it took so long to respond on this one. The driver currently doesn't support TLS. There seems to be an issue with the authentication implementation. I will fix as soon as I can and see if I can get TLS in there.

**Comment by jrahaim** [comment]
Thanks for getting back to me.. If there is anything I can do to help let me know.

**Comment by jjacobson93** [comment]
I fixed the authentication issue and added functionality for SSL, but I can't seem to get it working with my self-signed certs.

The `r.connect()` method has an `ssl:` parameter which takes in an instance of `SSLService.Configuration`. See here for documentation on how to use: [IBM-Swift/BlueSSLService](https://github.com/IBM-Swift/BlueSSLService).

Let me know if you have any success.

**Comment by jrahaim** [comment]
Thanks.. I am getting 
> fatal error: unexpectedly found nil while unwrapping an Optional value
on `let r = RethinkDB.r`

with an unhelpful stack trace. I am not 100% sure all my dependencies are correct, so I am digging some more.

**Comment by jrahaim** [comment]
👍 Works like a charm connecting to both local host, and across the wire.

FYI: For Free, valid signed certs I am using 
letsencrypt.org

**Comment by jjacobson93** [comment]
Perfect! Glad it works!
